name: "Terraform Cloudflare Apply"

on:
  push:
    branches: [main]
    paths:
      - "cloudflare/**"
      - "modules/cloudflare/**"

permissions:
  contents: read

jobs:
  apply:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      working-directory: cloudflare
      provider-token-name: CLOUDFLARE_API_TOKEN
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      PROVIDER_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
