name: "Doppler Provider"

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "doppler/**"

jobs:
  apply:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      module-path: doppler
      provider-token-name: DOPPLER_TOKEN
    secrets: inherit
