name: "Terraform Doppler Apply"

on:
  push:
    branches: [main]
    paths:
      - "doppler/**"
      - "modules/doppler/**"

permissions:
  contents: read

jobs:
  apply:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      working-directory: doppler
      provider-token-name: DOPPLER_TOKEN
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      PROVIDER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
