name: "Honeycomb Provider"

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "honeycomb/**"

jobs:
  apply:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      module-path: honeycomb
      provider-token-name: HONEYCOMB_API_KEY
    secrets: inherit
