name: "OCI Provider"

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "oci/**"

jobs:
  apply:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      module-path: oci
    secrets: inherit
