name: "Terraform Sentry Apply"

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "sentry/**"

jobs:
  apply:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      module-path: sentry
      provider-token-name: SENTRY_AUTH_TOKEN
    secrets:
      PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
      PROVIDER_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
