name: "Tailscale Provider"

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "tailscale/**"

jobs:
  apply:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      module-path: tailscale
      provider-token-name: TAILSCALE_API_KEY
    secrets: inherit
